### ISSUE TITLE
[Suggestion] Oh The Biomes You'll Go Blueberries support

### ISSUE THREAD

**Issue by MarioSMB** [team-abnormals/berry-good#17]
BYG adds a plant very similar to sweet berries, called Blueberries. It would be cool if those could be supported by this mod, so they aren't planted while being eaten.

**Comment by bageldotjpg** [comment]
That would be preferably done on their end since it is adding a whole new item

**Comment by MarioSMB** [comment]
They are unwilling to do so, can you please reconsider? https://github.com/CorgiTaco/BYG/issues/420

**Comment by bageldotjpg** [comment]
Sorry, we will not be.
We don't want to fall into a loophole of adding support for every mod that adds a new type of berry.
Plus we'd have to do a bunch of forge registries checks and stuff when they could have a simple even that just checks if berry good is loaded, and in addition they would make the texture so that it matches their mods art style.

**Comment by MarioSMB** [comment]
For future cases, I'd like to suggest that you please reach out to any mod developers directly whose mods include berries that should be supported by your mod.  
As a player, jumping back and forth between issue reports that have been closed because neither side wants to do it is not a good way to handle cross-compatibility... it looks like BYG will be adding their own version of pips independently from Berry Good.
