### ISSUE TITLE
On the topic of a fabric port.

### ISSUE THREAD

**Issue by maximumpower55** [team-abnormals/berry-good#28]
I have gotten the latest 1.18.x commit of berry good running on fabric with full feature parity. I have done this by
- Replacing all references to blueprint with mixins and vanilla methods tho. I had to remove some datagen stuff because of this
- Switching the RightClickBlock event to a fabric api event callback
- Replaced the hacky reflection used to make glow berries make you glow when eaten with a simple mixin
- Replacing the milk bucket tag with a fabric api conventional item tag and milk lib
- Making the logo into a 256x256 square with still keeping the aspect ratio for modmenu support

![2022-07-20_19 21 20](https://user-images.githubusercontent.com/62370320/180300672-f9036f18-12b6-41cd-97ed-c2802d4fd3d9.png)

Currently because of the ARR (All Rights Reserved) license, I'm only using this port for private / personal use.
I'm making this issue for 2 things.
- To ask if i need to make the github repo that contains the fabric port private
- if we can talk about giving me permission to release this port in some form

Ending statement: I really like this mod, and used it back in the days where I made tons of 1.16 forge modpacks for me and my friends, and would be happy to see if I can release this port in some form

**Comment by bageldotjpg** [comment]
Unfortunately, we are not allowing Fabric ports of our mods, this is out of no spite for Fabric, it is just merely something we do not want due to additional troubles associated with having them out.
* If we have one mod fabric ported, people will beg or expect the others so it is better for not at all in our opinion
* We have a fair few mods that update quite sporadically, making sure fabric versions always keep up would be hard. See the Farmer's Delight fabric port.
* Plenty of room for inconsistency with the Forge versions.
* People coming to us with questions, bugs, reports, and demands about the Fabric versions

I'm sorry if this is not the answer you were hoping for and unfortunately due to the license we would appreciate if you privated the github and did not redistribute this. Thank you and sorry!

**Comment by maximumpower55** [comment]
Sorry for the late reply (I don't check my email a lot), Thanks for answering and will be privating the github repo now!
